---
standard_vlans:
  - name: Data_VLAN
    vlan_id: 10
  - name: Voice_VLAN
    vlan_id: 20

ntp_server: "10.0.0.5"

motd_text: |
  =========================================
  UNAUTHORIZED ACCESS STRICTLY PROHIBITED.
  All activity on this device is logged.
  =========================================